// Data-driven class definitions: the Warrior (melee/Fury) and Hunter (ranged/Focus)
// kits, their primary stat, and their resource behaviour. Adding the Priest in 0.2.1
// is a data change here. Numbers are `v1` tuning targets (docs/design/CLASS_DESIGN.md).

import type { ClassId, PrimaryStatId } from '../core/ecs/components';
import type { AbilityDef } from './combat/abilities';
import { Status } from './combat/statuses';

export interface ResourceConfig {
  name: string;
  max: number;
  /** Regenerated every second, always. */
  regenPerSec: number;
  /** Added per second while in combat (e.g. Warrior Battle Hardened). */
  inCombatRegen: number;
  /** Lost per second while out of combat (e.g. Fury decay). */
  decayOocPerSec: number;
  /** Whether the pool starts full (Focus) or empty (Fury). */
  startsFull: boolean;
}

/** A talent "choice node": pick one of two abilities for a single hotbar slot. */
export interface ChoiceNode {
  id: string;
  unlockLevel: number;
  options: readonly [AbilityDef, AbilityDef];
}

export interface ClassDef {
  id: ClassId;
  name: string;
  primaryStatId: PrimaryStatId;
  resource: ResourceConfig;
  /** Always-on abilities (hotbar slots in declaration order). */
  abilities: readonly AbilityDef[];
  /** Choice nodes appended after the base kit (one hotbar slot each). */
  choiceNodes: readonly ChoiceNode[];
}

const WARRIOR_ABILITIES: AbilityDef[] = [
  {
    id: 'cleaving-strike',
    name: 'Cleaving Strike',
    unlockLevel: 1,
    base: 4,
    coeff: 0.7,
    damageType: 'physical',
    cost: 0,
    furyGain: 12,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'frontalSplash',
    range: 6,
    radius: 2.5,
  },
  {
    id: 'sunder',
    name: 'Sunder',
    unlockLevel: 1,
    base: 6,
    coeff: 1.6,
    damageType: 'physical',
    cost: 30,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'target',
    range: 6,
    radius: 0,
    debuff: { id: Status.ArmorBreak, durationSec: 8, magnitude: 12 },
  },
  {
    id: 'whirl',
    name: 'Whirl',
    unlockLevel: 3,
    base: 5,
    coeff: 0.9,
    damageType: 'physical',
    cost: 35,
    furyGain: 0,
    cooldown: 6,
    triggersGcd: true,
    targeting: 'selfAoE',
    range: 0,
    radius: 4,
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    unlockLevel: 5,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 0,
    furyGain: 0,
    cooldown: 18,
    triggersGcd: false,
    targeting: 'self',
    range: 0,
    radius: 0,
    selfBuff: { id: Status.Bulwark, durationSec: 4, magnitude: 0.5 },
  },
  {
    id: 'charge',
    name: 'Charge',
    unlockLevel: 7,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 0,
    furyGain: 15,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'charge',
    range: 18,
    radius: 0,
    debuff: { id: Status.Root, durationSec: 1, magnitude: 1 },
  },
  {
    id: 'second-wind',
    name: 'Second Wind',
    unlockLevel: 9,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 40,
    furyGain: 0,
    cooldown: 14,
    triggersGcd: true,
    targeting: 'heal',
    range: 0,
    radius: 0,
    heal: { base: 10, coeff: 0.5, missingHpPct: 0.25 },
  },
  {
    id: 'pommel-strike',
    name: 'Pommel Strike',
    unlockLevel: 12,
    base: 4,
    coeff: 0.4,
    damageType: 'physical',
    cost: 0,
    furyGain: 8,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'interrupt',
    range: 6,
    radius: 0,
    debuff: { id: Status.Silence, durationSec: 3, magnitude: 1 },
  },
  {
    id: 'earthsplitter',
    name: 'Earthsplitter',
    unlockLevel: 16,
    base: 4,
    coeff: 0.5,
    damageType: 'physical',
    cost: 35,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'groundAoE',
    range: 10,
    radius: 3.5,
    aoeTtl: 4,
    aoeTick: 1,
  },
];

const HUNTER_ABILITIES: AbilityDef[] = [
  {
    id: 'quick-shot',
    name: 'Quick Shot',
    unlockLevel: 1,
    base: 3,
    coeff: 0.7,
    damageType: 'physical',
    cost: 0,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'projectile',
    range: 25,
    radius: 0,
    projectileSpeed: 30,
  },
  {
    id: 'piercing-arrow',
    name: 'Piercing Arrow',
    unlockLevel: 1,
    base: 5,
    coeff: 1.1,
    damageType: 'physical',
    cost: 35,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'projectile',
    range: 25,
    radius: 0,
    projectileSpeed: 34,
  },
  {
    id: 'volley',
    name: 'Volley',
    unlockLevel: 3,
    base: 5,
    coeff: 0.8,
    damageType: 'physical',
    cost: 40,
    furyGain: 0,
    cooldown: 6,
    triggersGcd: true,
    targeting: 'cone',
    range: 16,
    radius: 0,
    coneHalfDeg: 30,
  },
  {
    id: 'hunters-mark',
    name: "Hunter's Mark",
    unlockLevel: 5,
    base: 1,
    coeff: 0,
    damageType: 'physical',
    cost: 15,
    furyGain: 0,
    cooldown: 10,
    triggersGcd: true,
    targeting: 'target',
    range: 25,
    radius: 0,
    debuff: { id: Status.Marked, durationSec: 12, magnitude: 0.12 },
  },
  {
    id: 'disengage',
    name: 'Disengage',
    unlockLevel: 7,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 0,
    furyGain: 0,
    cooldown: 10,
    triggersGcd: false,
    targeting: 'dash',
    range: 0,
    radius: 0,
    dashDistance: 6,
    selfBuff: { id: Status.Fleet, durationSec: 2, magnitude: 0.3 },
  },
  {
    id: 'snare-trap',
    name: 'Snare Trap',
    unlockLevel: 9,
    base: 4,
    coeff: 0.5,
    damageType: 'physical',
    cost: 20,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'trap',
    range: 0,
    radius: 0,
    trapRadius: 2.2,
    trapRootSec: 3,
    trapTtl: 30,
  },
  {
    id: 'scatter-shot',
    name: 'Scatter Shot',
    unlockLevel: 12,
    base: 3,
    coeff: 0.4,
    damageType: 'physical',
    cost: 15,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'interrupt',
    range: 25,
    radius: 0,
    debuff: { id: Status.Silence, durationSec: 3, magnitude: 1 },
  },
  {
    id: 'rain-of-arrows',
    name: 'Rain of Arrows',
    unlockLevel: 16,
    base: 4,
    coeff: 0.5,
    damageType: 'physical',
    cost: 40,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'groundAoE',
    range: 22,
    radius: 4,
    aoeTtl: 4,
    aoeTick: 1,
  },
];

const PRIEST_ABILITIES: AbilityDef[] = [
  {
    id: 'smite',
    name: 'Smite',
    unlockLevel: 1,
    base: 3,
    coeff: 0.8,
    damageType: 'holy',
    cost: 8,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'projectile',
    range: 25,
    radius: 0,
    projectileSpeed: 28,
  },
  {
    id: 'searing-light',
    name: 'Searing Light',
    unlockLevel: 1,
    base: 5,
    coeff: 1.2,
    damageType: 'holy',
    cost: 18,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'target',
    range: 25,
    radius: 0,
    castTime: 1.2,
  },
  {
    id: 'holy-nova',
    name: 'Holy Nova',
    unlockLevel: 3,
    base: 4,
    coeff: 0.6,
    damageType: 'holy',
    cost: 22,
    furyGain: 0,
    cooldown: 6,
    triggersGcd: true,
    targeting: 'selfAoE',
    range: 0,
    radius: 5,
    heal: { base: 6, coeff: 0.4 },
  },
  {
    id: 'mend',
    name: 'Mend',
    unlockLevel: 5,
    base: 0,
    coeff: 0,
    damageType: 'holy',
    cost: 18,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'heal',
    range: 0,
    radius: 0,
    heal: { base: 10, coeff: 1.2 },
  },
  {
    id: 'aegis',
    name: 'Aegis',
    unlockLevel: 7,
    base: 0,
    coeff: 0,
    damageType: 'holy',
    cost: 20,
    furyGain: 0,
    cooldown: 14,
    triggersGcd: false,
    targeting: 'shield',
    range: 0,
    radius: 0,
    shield: { coeff: 1.2, durationSec: 10 },
  },
  {
    id: 'atonement',
    name: 'Atonement',
    unlockLevel: 9,
    base: 0,
    coeff: 0,
    damageType: 'holy',
    cost: 0,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: false,
    targeting: 'toggle',
    range: 0,
    radius: 0,
    toggle: { id: Status.Atonement, magnitude: 0.3 },
  },
  {
    id: 'silence',
    name: 'Silence',
    unlockLevel: 12,
    base: 2,
    coeff: 0.3,
    damageType: 'holy',
    cost: 12,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'interrupt',
    range: 25,
    radius: 0,
    debuff: { id: Status.Silence, durationSec: 4, magnitude: 1 },
  },
  {
    id: 'consecration',
    name: 'Consecration',
    unlockLevel: 16,
    base: 4,
    coeff: 0.5,
    damageType: 'holy',
    cost: 25,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'groundAoE',
    range: 22,
    radius: 4,
    aoeTtl: 4,
    aoeTick: 1,
  },
];

// ── Choice nodes (Lv 14 / Lv 18): pick one of two for a hotbar slot ──────────
// Each pair offers a clearly different option (defensive vs offensive, burst vs
// control) so the choice "produces distinct play" per the 0.4.0 acceptance.

const WARRIOR_CHOICES: ChoiceNode[] = [
  {
    id: 'war-a',
    unlockLevel: 14,
    options: [
      {
        id: 'rallying-cry',
        name: 'Rallying Cry',
        unlockLevel: 14,
        base: 0,
        coeff: 0,
        damageType: 'physical',
        cost: 0,
        furyGain: 0,
        cooldown: 24,
        triggersGcd: false,
        targeting: 'self',
        range: 0,
        radius: 0,
        selfBuff: { id: Status.Bulwark, durationSec: 8, magnitude: 0.4 },
      },
      {
        id: 'bloodthirst',
        name: 'Bloodthirst',
        unlockLevel: 14,
        base: 8,
        coeff: 1.2,
        damageType: 'physical',
        cost: 25,
        furyGain: 0,
        cooldown: 6,
        triggersGcd: true,
        targeting: 'target',
        range: 6,
        radius: 0,
        heal: { base: 6, coeff: 0.4 },
      },
    ],
  },
  {
    id: 'war-b',
    unlockLevel: 18,
    options: [
      {
        id: 'unbreakable',
        name: 'Unbreakable',
        unlockLevel: 18,
        base: 0,
        coeff: 0,
        damageType: 'physical',
        cost: 0,
        furyGain: 0,
        cooldown: 30,
        triggersGcd: false,
        targeting: 'shield',
        range: 0,
        radius: 0,
        shield: { coeff: 2.5, durationSec: 8 },
      },
      {
        id: 'ravager',
        name: 'Ravager',
        unlockLevel: 18,
        base: 7,
        coeff: 1,
        damageType: 'physical',
        cost: 45,
        furyGain: 0,
        cooldown: 15,
        triggersGcd: true,
        targeting: 'selfAoE',
        range: 0,
        radius: 5,
      },
    ],
  },
];

const HUNTER_CHOICES: ChoiceNode[] = [
  {
    id: 'hun-a',
    unlockLevel: 14,
    options: [
      {
        id: 'aimed-shot',
        name: 'Aimed Shot',
        unlockLevel: 14,
        base: 9,
        coeff: 1.6,
        damageType: 'physical',
        cost: 35,
        furyGain: 0,
        cooldown: 8,
        triggersGcd: true,
        targeting: 'projectile',
        range: 28,
        radius: 0,
        projectileSpeed: 40,
      },
      {
        id: 'explosive-trap',
        name: 'Explosive Trap',
        unlockLevel: 14,
        base: 7,
        coeff: 0.9,
        damageType: 'fire',
        cost: 30,
        furyGain: 0,
        cooldown: 14,
        triggersGcd: true,
        targeting: 'trap',
        range: 0,
        radius: 0,
        trapRadius: 3,
        trapRootSec: 1.5,
        trapTtl: 30,
      },
    ],
  },
  {
    id: 'hun-b',
    unlockLevel: 18,
    options: [
      {
        id: 'barrage',
        name: 'Barrage',
        unlockLevel: 18,
        base: 6,
        coeff: 1,
        damageType: 'physical',
        cost: 45,
        furyGain: 0,
        cooldown: 12,
        triggersGcd: true,
        targeting: 'cone',
        range: 18,
        radius: 0,
        coneHalfDeg: 35,
      },
      {
        id: 'camouflage',
        name: 'Camouflage',
        unlockLevel: 18,
        base: 0,
        coeff: 0,
        damageType: 'physical',
        cost: 0,
        furyGain: 0,
        cooldown: 24,
        triggersGcd: false,
        targeting: 'self',
        range: 0,
        radius: 0,
        selfBuff: { id: Status.Bulwark, durationSec: 6, magnitude: 0.4 },
      },
    ],
  },
];

const PRIEST_CHOICES: ChoiceNode[] = [
  {
    id: 'pri-a',
    unlockLevel: 14,
    options: [
      {
        id: 'penance',
        name: 'Penance',
        unlockLevel: 14,
        base: 7,
        coeff: 1.3,
        damageType: 'holy',
        cost: 20,
        furyGain: 0,
        cooldown: 8,
        triggersGcd: true,
        targeting: 'target',
        range: 25,
        radius: 0,
        heal: { base: 5, coeff: 0.5 },
      },
      {
        id: 'holy-fire',
        name: 'Holy Fire',
        unlockLevel: 14,
        base: 8,
        coeff: 1.6,
        damageType: 'holy',
        cost: 22,
        furyGain: 0,
        cooldown: 7,
        triggersGcd: true,
        targeting: 'target',
        range: 25,
        radius: 0,
        castTime: 1.2,
      },
    ],
  },
  {
    id: 'pri-b',
    unlockLevel: 18,
    options: [
      {
        id: 'divine-aegis',
        name: 'Divine Aegis',
        unlockLevel: 18,
        base: 0,
        coeff: 0,
        damageType: 'holy',
        cost: 25,
        furyGain: 0,
        cooldown: 24,
        triggersGcd: false,
        targeting: 'shield',
        range: 0,
        radius: 0,
        shield: { coeff: 2.2, durationSec: 10 },
      },
      {
        id: 'divine-star',
        name: 'Divine Star',
        unlockLevel: 18,
        base: 6,
        coeff: 1,
        damageType: 'holy',
        cost: 30,
        furyGain: 0,
        cooldown: 9,
        triggersGcd: true,
        targeting: 'selfAoE',
        range: 0,
        radius: 5,
        heal: { base: 5, coeff: 0.4 },
      },
    ],
  },
];

const CLASSES: Record<ClassId, ClassDef> = {
  warrior: {
    id: 'warrior',
    name: 'Warrior',
    primaryStatId: 'STR',
    resource: {
      name: 'Fury',
      max: 100,
      regenPerSec: 0,
      inCombatRegen: 3,
      decayOocPerSec: 6,
      startsFull: false,
    },
    abilities: WARRIOR_ABILITIES,
    choiceNodes: WARRIOR_CHOICES,
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    primaryStatId: 'DEX',
    resource: {
      name: 'Focus',
      max: 100,
      regenPerSec: 10,
      inCombatRegen: 0,
      decayOocPerSec: 0,
      startsFull: true,
    },
    abilities: HUNTER_ABILITIES,
    choiceNodes: HUNTER_CHOICES,
  },
  priest: {
    id: 'priest',
    name: 'Priest',
    primaryStatId: 'SPR',
    resource: {
      name: 'Mana',
      max: 100,
      regenPerSec: 8,
      inCombatRegen: 0,
      decayOocPerSec: 0,
      startsFull: true,
    },
    abilities: PRIEST_ABILITIES,
    choiceNodes: PRIEST_CHOICES,
  },
};

export function getClass(id: ClassId): ClassDef {
  return CLASSES[id];
}

/** Total hotbar slots for a class: base abilities + one per choice node (fixed). */
export function kitLength(cls: ClassDef): number {
  return cls.abilities.length + cls.choiceNodes.length;
}

/** The player's ordered kit: base abilities, then the selected option per choice node. */
export function resolveKit(cls: ClassDef, choices?: Record<string, number>): AbilityDef[] {
  const kit: AbilityDef[] = [...cls.abilities];
  for (const node of cls.choiceNodes) {
    const pick = choices?.[node.id] === 1 ? 1 : 0;
    kit.push(node.options[pick]);
  }
  return kit;
}
