// Data-driven class definitions: the Warrior (melee/Fury) and Hunter (ranged/Focus)
// kits, their primary stat, and their resource behaviour. Adding the Priest in 0.2.1
// is a data change here. Numbers are `v1` tuning targets (docs/design/CLASS_DESIGN.md).

import type { ClassId, PrimaryStatId } from '../core/ecs/components';
import type { AbilityDef } from './combat/abilities';
import { Status } from './combat/statuses';

export interface ResourceConfig {
  name: string;
  max: number;
  /** Regenerated every second, always. */
  regenPerSec: number;
  /** Added per second while in combat (e.g. Warrior Battle Hardened). */
  inCombatRegen: number;
  /** Lost per second while out of combat (e.g. Fury decay). */
  decayOocPerSec: number;
  /** Whether the pool starts full (Focus) or empty (Fury). */
  startsFull: boolean;
}

export interface ClassDef {
  id: ClassId;
  name: string;
  primaryStatId: PrimaryStatId;
  resource: ResourceConfig;
  abilities: readonly AbilityDef[];
}

const WARRIOR_ABILITIES: AbilityDef[] = [
  {
    id: 'cleaving-strike',
    name: 'Cleaving Strike',
    unlockLevel: 1,
    base: 4,
    coeff: 0.7,
    damageType: 'physical',
    cost: 0,
    furyGain: 12,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'frontalSplash',
    range: 6,
    radius: 2.5,
  },
  {
    id: 'sunder',
    name: 'Sunder',
    unlockLevel: 1,
    base: 6,
    coeff: 1.6,
    damageType: 'physical',
    cost: 30,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'target',
    range: 6,
    radius: 0,
    debuff: { id: Status.ArmorBreak, durationSec: 8, magnitude: 12 },
  },
  {
    id: 'whirl',
    name: 'Whirl',
    unlockLevel: 3,
    base: 5,
    coeff: 0.9,
    damageType: 'physical',
    cost: 35,
    furyGain: 0,
    cooldown: 6,
    triggersGcd: true,
    targeting: 'selfAoE',
    range: 0,
    radius: 4,
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    unlockLevel: 5,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 0,
    furyGain: 0,
    cooldown: 18,
    triggersGcd: false,
    targeting: 'self',
    range: 0,
    radius: 0,
    selfBuff: { id: Status.Bulwark, durationSec: 4, magnitude: 0.5 },
  },
  {
    id: 'charge',
    name: 'Charge',
    unlockLevel: 7,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 0,
    furyGain: 15,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'charge',
    range: 18,
    radius: 0,
    debuff: { id: Status.Root, durationSec: 1, magnitude: 1 },
  },
  {
    id: 'second-wind',
    name: 'Second Wind',
    unlockLevel: 9,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 40,
    furyGain: 0,
    cooldown: 14,
    triggersGcd: true,
    targeting: 'heal',
    range: 0,
    radius: 0,
    heal: { base: 10, coeff: 0.5, missingHpPct: 0.25 },
  },
  {
    id: 'pommel-strike',
    name: 'Pommel Strike',
    unlockLevel: 12,
    base: 4,
    coeff: 0.4,
    damageType: 'physical',
    cost: 0,
    furyGain: 8,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'interrupt',
    range: 6,
    radius: 0,
    debuff: { id: Status.Silence, durationSec: 3, magnitude: 1 },
  },
  {
    id: 'earthsplitter',
    name: 'Earthsplitter',
    unlockLevel: 16,
    base: 4,
    coeff: 0.5,
    damageType: 'physical',
    cost: 35,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'groundAoE',
    range: 10,
    radius: 3.5,
    aoeTtl: 4,
    aoeTick: 1,
  },
];

const HUNTER_ABILITIES: AbilityDef[] = [
  {
    id: 'quick-shot',
    name: 'Quick Shot',
    unlockLevel: 1,
    base: 3,
    coeff: 0.7,
    damageType: 'physical',
    cost: 0,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'projectile',
    range: 25,
    radius: 0,
    projectileSpeed: 30,
  },
  {
    id: 'piercing-arrow',
    name: 'Piercing Arrow',
    unlockLevel: 1,
    base: 5,
    coeff: 1.1,
    damageType: 'physical',
    cost: 35,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'projectile',
    range: 25,
    radius: 0,
    projectileSpeed: 34,
  },
  {
    id: 'volley',
    name: 'Volley',
    unlockLevel: 3,
    base: 5,
    coeff: 0.8,
    damageType: 'physical',
    cost: 40,
    furyGain: 0,
    cooldown: 6,
    triggersGcd: true,
    targeting: 'cone',
    range: 16,
    radius: 0,
    coneHalfDeg: 30,
  },
  {
    id: 'hunters-mark',
    name: "Hunter's Mark",
    unlockLevel: 5,
    base: 1,
    coeff: 0,
    damageType: 'physical',
    cost: 15,
    furyGain: 0,
    cooldown: 10,
    triggersGcd: true,
    targeting: 'target',
    range: 25,
    radius: 0,
    debuff: { id: Status.Marked, durationSec: 12, magnitude: 0.12 },
  },
  {
    id: 'disengage',
    name: 'Disengage',
    unlockLevel: 7,
    base: 0,
    coeff: 0,
    damageType: 'physical',
    cost: 0,
    furyGain: 0,
    cooldown: 10,
    triggersGcd: false,
    targeting: 'dash',
    range: 0,
    radius: 0,
    dashDistance: 6,
    selfBuff: { id: Status.Fleet, durationSec: 2, magnitude: 0.3 },
  },
  {
    id: 'snare-trap',
    name: 'Snare Trap',
    unlockLevel: 9,
    base: 4,
    coeff: 0.5,
    damageType: 'physical',
    cost: 20,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'trap',
    range: 0,
    radius: 0,
    trapRadius: 2.2,
    trapRootSec: 3,
    trapTtl: 30,
  },
  {
    id: 'scatter-shot',
    name: 'Scatter Shot',
    unlockLevel: 12,
    base: 3,
    coeff: 0.4,
    damageType: 'physical',
    cost: 15,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'interrupt',
    range: 25,
    radius: 0,
    debuff: { id: Status.Silence, durationSec: 3, magnitude: 1 },
  },
  {
    id: 'rain-of-arrows',
    name: 'Rain of Arrows',
    unlockLevel: 16,
    base: 4,
    coeff: 0.5,
    damageType: 'physical',
    cost: 40,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'groundAoE',
    range: 22,
    radius: 4,
    aoeTtl: 4,
    aoeTick: 1,
  },
];

const PRIEST_ABILITIES: AbilityDef[] = [
  {
    id: 'smite',
    name: 'Smite',
    unlockLevel: 1,
    base: 3,
    coeff: 0.8,
    damageType: 'holy',
    cost: 8,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'projectile',
    range: 25,
    radius: 0,
    projectileSpeed: 28,
  },
  {
    id: 'searing-light',
    name: 'Searing Light',
    unlockLevel: 1,
    base: 5,
    coeff: 1.2,
    damageType: 'holy',
    cost: 18,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'target',
    range: 25,
    radius: 0,
    castTime: 1.2,
  },
  {
    id: 'holy-nova',
    name: 'Holy Nova',
    unlockLevel: 3,
    base: 4,
    coeff: 0.6,
    damageType: 'holy',
    cost: 22,
    furyGain: 0,
    cooldown: 6,
    triggersGcd: true,
    targeting: 'selfAoE',
    range: 0,
    radius: 5,
    heal: { base: 6, coeff: 0.4 },
  },
  {
    id: 'mend',
    name: 'Mend',
    unlockLevel: 5,
    base: 0,
    coeff: 0,
    damageType: 'holy',
    cost: 18,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: true,
    targeting: 'heal',
    range: 0,
    radius: 0,
    heal: { base: 10, coeff: 1.2 },
  },
  {
    id: 'aegis',
    name: 'Aegis',
    unlockLevel: 7,
    base: 0,
    coeff: 0,
    damageType: 'holy',
    cost: 20,
    furyGain: 0,
    cooldown: 14,
    triggersGcd: false,
    targeting: 'shield',
    range: 0,
    radius: 0,
    shield: { coeff: 1.2, durationSec: 10 },
  },
  {
    id: 'atonement',
    name: 'Atonement',
    unlockLevel: 9,
    base: 0,
    coeff: 0,
    damageType: 'holy',
    cost: 0,
    furyGain: 0,
    cooldown: 0,
    triggersGcd: false,
    targeting: 'toggle',
    range: 0,
    radius: 0,
    toggle: { id: Status.Atonement, magnitude: 0.3 },
  },
  {
    id: 'silence',
    name: 'Silence',
    unlockLevel: 12,
    base: 2,
    coeff: 0.3,
    damageType: 'holy',
    cost: 12,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: false,
    targeting: 'interrupt',
    range: 25,
    radius: 0,
    debuff: { id: Status.Silence, durationSec: 4, magnitude: 1 },
  },
  {
    id: 'consecration',
    name: 'Consecration',
    unlockLevel: 16,
    base: 4,
    coeff: 0.5,
    damageType: 'holy',
    cost: 25,
    furyGain: 0,
    cooldown: 12,
    triggersGcd: true,
    targeting: 'groundAoE',
    range: 22,
    radius: 4,
    aoeTtl: 4,
    aoeTick: 1,
  },
];

const CLASSES: Record<ClassId, ClassDef> = {
  warrior: {
    id: 'warrior',
    name: 'Warrior',
    primaryStatId: 'STR',
    resource: {
      name: 'Fury',
      max: 100,
      regenPerSec: 0,
      inCombatRegen: 3,
      decayOocPerSec: 6,
      startsFull: false,
    },
    abilities: WARRIOR_ABILITIES,
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    primaryStatId: 'DEX',
    resource: {
      name: 'Focus',
      max: 100,
      regenPerSec: 10,
      inCombatRegen: 0,
      decayOocPerSec: 0,
      startsFull: true,
    },
    abilities: HUNTER_ABILITIES,
  },
  priest: {
    id: 'priest',
    name: 'Priest',
    primaryStatId: 'SPR',
    resource: {
      name: 'Mana',
      max: 100,
      regenPerSec: 8,
      inCombatRegen: 0,
      decayOocPerSec: 0,
      startsFull: true,
    },
    abilities: PRIEST_ABILITIES,
  },
};

export function getClass(id: ClassId): ClassDef {
  return CLASSES[id];
}
